### PR TITLE
docs: fix grammar errors in manual

### PR DESCRIPTION
**Pull request by IRod22**
I found a few grammar errors in English version of the Manual, so I thought I would fix them to make the Manual more clear.

### CODE REVIEW

**Comment by kyubuns** [comment]
Very helpful! Thank you!

**Comment by IRod22** [comment]
@kyubuns, you are welcome. Do you want me to fix any grammar errors in the docs in `kyubuns/AkyuiUnity.XD` or `kyubuns/AnKuchen` for you?

**Comment by kyubuns** [comment]
@IRod22 
Very glad to hear that!
If you can, please do.

**Comment by IRod22** [comment]
@kyubuns, I found a typo and fixed it in #46.

**Pull request merged**
